name: Docker Build and Push

on:
  push:
    branches: [ main ]

     
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: 
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.REPOS }}
          password: ${{ secrets.TOKEN }}
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      # Build and push the first image
      - name: Build and push image 1
        uses: docker/build-push-action@v6
        with:
          context: ./core/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ vars.REPOSITORY }}/image1:latest
            ghcr.io/${{ vars.REPOSITORY }}/image1:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push the second image
      - name: Build and push image 2
        uses: docker/build-push-action@v6
        with:
          context: ./js-compressor/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ vars.REPOSITORY }}/image2:latest
            ghcr.io/${{ vars.REPOSITORY }}/image2:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
