name: Docker Build and Push

on:
  push:
    branches: [ main ]

     
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: 
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.REPOS }}
          password: ${{ secrets.TOKEN }}
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      # Build and push the first image
      - name: Build and push image 1
        uses: docker/build-push-action@v6
        with:
          context: ./core
          push: false
          tags: |
            ghcr.io/${{ vars.REPOSITORY }}/image1:latest
            ghcr.io/${{ vars.REPOSITORY }}/image1:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build and push the second image
      - name: Build and push image 2
        uses: docker/build-push-action@v6
        with:
          context: ./js-compressor
          push: false
          tags: |
            ghcr.io/${{ vars.REPOSITORY }}/image2:latest
            ghcr.io/${{ vars.REPOSITORY }}/image2:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Slim Docker image1
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: "false"  # Disables HTTP probing during slimming
        with:
          target: ghcr.io/${{ vars.REPOSITORY }}/image1:latest  
          tag:  ghcr.io/${{ vars.REPOSITORY }}/image1:slim 
   
      - name: Slim Docker image2
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: "false"  # Disables HTTP probing during slimming
        with:
          target: ghcr.io/${{ vars.REPOSITORY }}/image2:latest  
          tag:  ghcr.io/${{ vars.REPOSITORY }}/image2:slim 

      - name: Push slimmed Docker image
        run: |
          docker push ghcr.io/${{ vars.REPOSITORY }}/image1:slim
          docker push ghcr.io/${{ vars.REPOSITORY }}/image2:slim

      
